---

- name: Install dev tool apt packages
  apt:
    pkg:
    - build-essential
    - clang-format
    - curl
    - git
    - neovim
    - tmux
    - vim-nox
    - wget
    - zlib1g
    - zlib1g-dev
    - zsh
  become: yes
