---

- name: Install Brave signing key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    id: D8BAD4DE7EE17AF52A834B2D0BB75829C2D4E821
  become: yes

- name: Install Brave apt repository
  apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ {{ansible_distribution_release}} main
  become: yes

- name: Install Brave apt package
  apt:
    pkg:
    - brave-browser
  become: yes
