---
# Travis CI support provided by: https://github.com/jonashackt/vagrant-travisci-libvrt
#   ...and viewers like you!

dist: bionic
language: python

# Install libvrt & KVM (see https://github.com/alvistack/ansible-role-virtualbox/blob/master/.travis.yml)
install:
- |
  echo 'Install travis-pls utility'
  pip install git+https://github.com/naftulikay/travis-pls

# For testing 'libvirt' locally on OSX (Mojave):
script:
- |
  set -xeuo pipefail
  export DOTFILES_PLATFORM=ubuntu
  sudo ./setup-$DOTFILES_PLATFORM/setup.sh
- |
  set -xeuo pipefail
  export DOTFILES_PLATFORM=ubuntu
  sudo ./config/config.sh
- |
  set -xeuo pipefail
  export DOTFILES_PLATFORM=ubuntu
  sudo '/vagrant/config/config.sh' vagrant
