---

- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Add homebrew cask-versions tap
  homebrew_tap:
    name: homebrew/cask-versions

- name: Upgrade all homebrew packages
  homebrew:
    upgrade_all: yes

- name: Upgrade all homebrew cask packages
  homebrew_cask:
    upgrade_all: yes
