---

- name: Create Go directories
  file:
    dest: "{{go_data_dir}}"
    state: directory
    mode: 0700

- name: Render Go Vars template file
  template:
    src: vars.sh
    dest: "{{shellrc_config_dir}}/0-go.sh"
    mode: 0400

- name: Link Go data directory
  file:
    src: "{{go_data_dir}}"
    dest: "~/go"
    state: link
    force: yes

- name: Install dev-tools go packages
  command:
    cmd: go get {{item}}
    creates: "{{go_data_dir}}/bin/{{item|basename}}"
  environment:
    GO111MODULE: "on"
  with_items:
  - github.com/mvdan/sh/cmd/shfmt
  - github.com/bazelbuild/buildtools/buildifier
  - github.com/bazelbuild/buildtools/buildozer

- name: Link Go Shell RC file
  file:
    src: "{{dotfiles_src_dir}}/go/{{item}}"
    dest: "{{shellrc_config_dir}}/{{item}}"
    state: link
    force: yes
  with_items:
  - 3-go.sh
