---

- name: Install neovim apt packages
  apt:
    pkg:
    - neovim
  become: yes

- name: Install Neovim build dependencies apt packages
  apt:
    pkg:
      - cmake
      - curl
      - gettext
      - ninja-build
      - unzip
  become: yes
