---

# TODO
# * add zoox role with dep on shellrc and bazel
#     link zoox shellrc file to `3-work.sh`
#     link zoox bazelrc file to `work.bazelrc`
- hosts: 127.0.0.1
  connection: local
  roles:
  - alacritty
  - bashrc
  - cargo
  - dircolors
  - fzf
  - gem
  - git
  - go
  - npm
  - pip
  - ssh-agent-canonicalize
  - tmux
  - vagrant
  - vim
  - worktree
  - zshrc
