---

# TODO: Switch to the Vagrant-approved method of installation 
# (i.e from a download on their website:
#   https://github.com/hashicorp/vagrant/issues/7529#issuecomment-229216232
#   https://www.vagrantup.com/downloads.html

- name: Install Vagrant signing key
  apt_key:
    id: D2BABDFD63EA9ECAB4E09C7228A873EA3C7C705F
    keyserver: hkp://keyserver.ubuntu.com:80
  become: yes

- name: Install Vagrant apt repository
  apt_repository:
    repo: deb https://vagrant-deb.linestarve.com/ any main
  become: yes

- name: Install Vagrant apt package
  apt:
    name: vagrant
  become: yes

# See: https://computingforgeeks.com/install-latest-vagrant-on-ubuntu-debian-kali-linux/
# Apparantly HashiCorp refuses to maintain a regular PPA:
#   https://github.com/hashicorp/vagrant-installers/issues/12
