---

- name: Download Vagrant signing key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: "{{hashicorp_signing_key}}"
    mode: "0644"
  become: yes

- name: Install Vagrant apt repository
  apt_repository:
    repo: "deb [arch={{arch}} signed-by={{hashicorp_signing_key}}] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main"
  vars:
    arch: "{{'arm64' if ansible_facts['architecture'] == 'arm64' else 'amd64'}}"
  become: yes

- name: Install Vagrant apt package
  apt:
    pkg:
    - vagrant
  become: yes
