---

- name: Download Vagrant signing key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: "{{hashicorp_signing_key}}"
    mode: "0644"
  become: yes

- name: Install Vagrant apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by={{hashicorp_signing_key}}] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main"
  become: yes

- name: Install Vagrant apt package
  apt:
    pkg:
    - vagrant
  become: yes
