---

- name: Link Vagrant Shell RC file
  file:
    src: "{{dotfiles_src_dir}}/vagrant/3-vagrant.sh"
    dest: "{{shellrc_config_dir}}/3-vagrant.sh"
    state: link
    follow: no
    force: yes

- name: Install Vagrant plugins
  command:
    cmd: vagrant plugin install {{item}}
  with_items:
  - vagrant-cachier
  - vagrant-lxc
  - vagrant-qemu
  - vagrant-sshfs

- name: Install other Vagrant plugins
  command:
    cmd: vagrant plugin install {{item}}
  with_items:
  - vagrant-libvirt
  when: ansible_facts["os_family"] != "Darwin"
