---

- name: Install Google signing key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    id: EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
  become: yes

- name: Install Chrome apt repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
  become: yes

- name: Install Chrome apt package
  apt:
    pkg:
    - google-chrome-stable
  become: yes
