---

- block:
  - name: Check if Google Chrome is installed
    command:
      cmd: which google-chrome-stable

  rescue:
  - name: Download Google signing key
    get_url:
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      dest: "{{google_signing_key}}"
      mode: "0644"
    become: yes

  - name: Install Chrome apt repository
    apt_repository:
      repo: "deb [arch={{arch}} signed-by={{google_signing_key}}] http://dl.google.com/linux/chrome/deb/ stable main"
    vars:
      arch: "{{'arm64' if ansible_facts['architecture'] == 'arm64' else 'amd64'}}"
    become: yes

  - name: Install Chrome apt package
    apt:
      pkg:
      - google-chrome-stable
    become: yes
