---

# Pattern borrowed from:
#   https://prefetch.net/blog/2017/08/27/using-ansible-to-verify-remote-file-checksums-with-get_url-lookup-and-stat/

- name: "Create Go download directory, if it doesn't exist"
  file:
    path: "{{ go_download_dest | dirname }}"
    state: directory
    mode: 0700

- name: "Downloading Go tarball version: {{ go_version }}"
  get_url:
    url: "{{ go_download_url }}"
    dest: "{{ go_download_dest }}"
    mode: 0600

- name: "Checksumming downloaded Go tarball"
  stat:
     checksum_algorithm: "sha256"
     path: "{{ go_download_dest }}"
  register: st

- name: "Halt and catch fire if SHA of Go tarball doesn't match"
  assert:
    that:
      - go_sha256 == st.stat.checksum
    msg: "SHA of downloaded Go tarball doesn't match!\n  Expected: {{ go_sha256 }}\n  Actual: {{  st.stat.checksum  }}"

- name: "Extract the Go tarball to {{ go_install_dest }}"
  unarchive:
    src: "{{ go_download_dest }}"
    dest: "{{ go_install_dest }}"
  when: go_sha256 == st.stat.checksum
