---

- name: Create Tmux directories
  file:
    dest: "{{item}}"
    state: directory
    mode: 0700
  with_items:
  - "{{tmux_config_dir}}"
  - "{{tmux_data_dir}}"
  - "{{tmux_plugins_data_dir}}"

- name: Render Tmux Vars template file
  template:
    src: vars.sh
    dest: "{{shellrc_config_dir}}/0-tmux.sh"
    mode: 0400

- name: Render Tmux config template files
  template:
    src: "{{item}}"
    dest: "{{tmux_config_dir}}/{{item}}"
    mode: 0400
  with_items:
  - tmux.conf

- name: Render Tmux executable template files
  template:
    src: "{{item}}"
    dest: "{{xdg_bin_home}}/{{item}}"
    mode: 0500
  with_items:
  - tmux-theme

- name: Link Tmux data directory
  file:
    src: "{{tmux_data_dir}}"
    dest: ~/.tmux
    state: link
    force: yes

- name: Link Tmux config file
  file:
    src: "{{tmux_config_dir}}/tmux.conf"
    dest: ~/.tmux.conf
    state: link
    force: yes

- name: Download Tmux TPM repository
  git:
    repo: "{{tmux_tpm_repo}}"
    dest: "{{tmux_tpm_data_dir}}"
    depth: 1

- name: Install Tmux plugins
  shell:
    executable: /bin/bash
    cmd: |
      if tmux info &>/dev/null; then
        tmux source ~/.tmux.conf
      fi
      export TMUX_PLUGIN_MANAGER_PATH='{{tmux_plugins_data_dir}}'
      {{tmux_tpm_data_dir}}/bin/install_plugins

- name: Link Tmux executable files
  file:
    src: "{{tmux_plugins_data_dir}}/tmux-mem-cpu-load/tmux-mem-cpu-load"
    dest: "{{xdg_bin_home}}/tmux-mem-cpu-load"
    state: link
    force: yes
