---

- name: Link Git Config file
  file:
    src: "{{dotfiles_src_dir}}/git/gitconfig"
    dest: "~/.gitconfig"
    state: link
    force: yes

- name: Link Git command files
  file:
    src: "{{dotfiles_src_dir}}/git/{{item}}"
    dest: "{{xdg_bin_home}}/{{item}}"
    state: link
    force: yes
  with_items:
  - git-push-retry
