---

- name: Download Docker signing key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: "{{docker_signing_key}}"
    mode: "0644"
  become: yes

- name: Install Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by={{docker_signing_key}}] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
  become: yes

- name: Install Docker apt packages
  apt:
    pkg:
    - docker-ce
    - docker-compose
  become: yes

- name: Add user to Docker group
  user:
    name: "{{lookup('env', 'USER')}}"
    groups:
    - docker
    append: yes
  become: yes
