---

- name: Install Docker signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  become: yes

- name: Install Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  become: yes

- name: Install Docker apt packages
  apt:
    pkg:
    - docker-ce
    - docker-compose
  become: yes

- name: Add user to Docker group
  user:
    name: "{{ansible_user}}"
    groups:
    - docker
    append: yes
  become: yes
