---

- name: Link Color Selector Shell RC files
  file:
    src: "{{dotfiles_src_dir}}/color-selector/{{item}}"
    dest: "{{shellrc_config_dir}}/{{item}}"
    state: link
    follow: no
    force: yes
  with_items:
  - 1-color-selector.sh

- name: Render Color Selector executable file
  template:
    src: color-selector
    dest: "{{xdg_bin_home}}/color-selector"
    mode: 0700
