---

- name: Download and unpack Vim release tarball
  unarchive:
    src: "{{vim_release_url}}"
    dest: "{{source_releases_data_dir}}"
    remote_src: yes

- name: Configure, make, and install Vim release (this will take a while)
  shell:
    chdir: "{{vim_release_dir}}/src"
    cmd: |
      set -ex
      ./configure \
          --with-features=huge \
          --disable-gui \
          --enable-cscope \
          --enable-luainterp=yes \
          --enable-multibyte \
          --enable-perlinterp=yes \
          --enable-pythoninterp=yes \
          --enable-python3interp=yes \
          --enable-rubyinterp=yes \
          --enable-terminal \
          --prefix={{xdg_prefix_home}}
      make
      make install
    creates: "{{xdg_bin_home}}/vim"

- name: Create Vim directories
  file:
    dest: "{{item}}"
    state: directory
    mode: 0700
  with_items:
  - "{{vim_config_dir}}"
  - "{{vim_config_dir}}/autoload"
  - "{{vim_data_dir}}"
  - "{{vim_data_dir}}/plugged"

- name: Render Vim Vars template file
  template:
    src: vars.sh
    dest: "{{shellrc_config_dir}}/0-vim.sh"
    mode: 0400

- name: Link Vim config files
  file:
    src: "{{dotfiles_src_dir}}/vim/{{item}}"
    dest: "{{vim_config_dir}}/{{item}}"
    state: link
    force: yes
  with_items:
  - vimrc
  - UltiSnips
  - pythonx

- name: Link Vim RC file
  file:
    src: "{{vim_config_dir}}/vimrc"
    dest: "{{item}}"
    state: link
    force: yes
  with_items:
  - ~/.vimrc
  - "{{vim_config_dir}}/init.vim"

- name: Unlink Vim RC directory
  file:
    path: "{{item}}"
    state: absent
  with_items:
  - ~/.vim
  - "{{xdg_config_home}}/nvim"

- name: Link Vim RC directory
  file:
    src: "{{vim_config_dir}}"
    dest: "{{item}}"
    state: link
  with_items:
  - ~/.vim
  - "{{xdg_config_home}}/nvim"

- name: Link Neovim data directory
  file:
    src: "{{vim_data_dir}}"
    dest: "{{xdg_data_home}}/nvim"
    state: link
    force: yes

- name: Download Vim Plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Link Vim Plugin directory
  file:
    src: "{{vim_data_dir}}/plugged"
    dest: "{{vim_config_dir}}/plugged"
    state: link
    force: yes

- name: Install Vim Plugins
  command:
    cmd: vim +PlugUpdate +:qa

- name: Link Shell RC files
  file:
    src: "{{dotfiles_src_dir}}/vim/3-vim.sh"
    dest: "{{shellrc_config_dir}}/3-vim.sh"
    state: link
    force: yes
