---

- name: Install system tool homebrew packages
  homebrew:
    name:
    - binutils
    - coreutils
    - diffutils
    - findutils
    - fswatch
    - gawk
    - gettext
    - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnu-which
    - gnutls
    - grep
    - gzip
    - htop
    - ifstat
    - iftop
    - ncdu
    - neofetch
    - nmap
    - rsync
    - watch
    - wdiff
    - wget
