---

- name: Install tmux apt packages
  apt:
    pkg:
    - tmux
  become: yes

- name: Install tmux build dependencies apt packages
  apt:
    pkg:
    - libncurses5-dev
    - libncursesw5-dev
    - libevent-dev
  become: yes
